<script type="text/javascript">
    var special_selected = false;
    var special_shipping_popup = new Window('special_shipping_popup',{
        className:'magento',
        title:'Special Shipping Products List',
        url: '<?php echo Mage::getUrl('custom/custom'); ?>',
        width:800,
        height:450,
        minimizable:false,
        maximizable:false,
        showEffectOptions:{
            duration:0.4
        },
    });
    special_shipping_popup.setZIndex(100);
</script>