<script type="text/javascript">
    var special_selected = false;
    var special_shipping_popup = new Window('special_shipping_popup',{
        className:'magento',
        title:'Special Shipping Products List',
        url: '<?php echo Mage::getUrl('custom/custom'); ?>',
        width:800,
        height:450,
        minimizable:false,
        maximizable:false,
        showEffectOptions:{
            duration:0.4
        },
        hideEffectOptions:{
            duration:0.4
//        },
//        closeCallback: function() {
//            if(!special_selected){
//                this.close();
//                return;
//            }
//            parent.window.location.reload();
        }
    });
    special_shipping_popup.setZIndex(100);
</script>