<style type="text/css">
    #loading-mask {
    background:background:url(../images/blank.gif) repeat;
    position:absolute;
    color:#d85909;
    font-size:1.1em;
    font-weight:bold;
    text-align:center;
    opacity:0.80;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)"; /* IE8 */
    z-index:500;
    }
#loading-mask .loader {
    position:fixed;
    top:45%;
    left:50%;
    width:120px;
    margin-left:-60px;
    padding:15px 60px;
    background:#fff4e9;
    border:2px solid #f1af73;
    color:#d85909;
    font-weight:bold;
    text-align:center;
    z-index:1000;
    }

</style>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Special Shipping Products List') ?></h1>
</div>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
                <span>If you don't want special shipping please click <a href="#" onclick="parent.special_shipping_popup.close();">here</a>
                </span>
            </li>
        </ul>
    </li>
</ul>
<table id="shopping-cart-table" class="data-table cart-table">
    <colgroup>
        <col width="1">
        <col>
        <col>
        <col width="1">
    </colgroup>
    <thead>
        <tr class="first last">
            <th rowspan="1" class="a-center"><span class="nobr">SKU</span></th>
            <th rowspan="1"><span class="nobr">Product Name</span></th>
            <th rowspan="1"><span class="nobr">Short Description</span></th>
            <th rowspan="1" class="a-center">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->getItems() as $_item): ?>
        <tr class="first odd">
            <td><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getSku(), 'sku') ?></td>
            <td>
                <h2 class="product-name">
                    <a href="http://uartest.lc/simple-product1.html"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a>
                </h2>
            </td>
            <td><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?></td>
            <td class="a-center">
                <a href="#" onclick="selectSpecialShipping(<?php echo $_item->getId() ?>);" title="select special shipping">select</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif',array('_area'=>'adminhtml','_package'=>'default','_theme'=>'default')) ?>" alt="<?php echo Mage::helper('custom')->__('Loading...') ?>"/><br/><?php echo Mage::helper('custom')->__('Please wait...') ?></p>
</div>
<script type="text/javascript">
    function selectSpecialShipping(productId)
    {
        new Ajax.Request('<?php echo Mage::getUrl('custom/custom/select') ?>', {
            parameters: {isAjax: 1, method: 'POST', product_id: productId},
            onLoading: function(){
                Element.show('loading-mask');
            },
            onSuccess: function(transport) {
                if (transport.responseText.isJSON()) {
                    var response = transport.responseText.evalJSON();
                    parent.window.location.reload();
                }
            },
            onComplete: function () {
                Element.hide('loading-mask');
            }
        });
    }
</script>