<div class="page-title title-buttons">
    <h1><?php echo $this->__('Special Shipping Products List') ?></h1>
</div>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
                <span>If you don't want special shipping please click <a href="#" onclick="parent.special_shipping_popup.close();">here</a>
                </span>
            </li>
        </ul>
    </li>
</ul>
<table id="shopping-cart-table" class="data-table cart-table">
    <colgroup>
        <col width="1">
        <col>
        <col>
        <col width="1">
    </colgroup>
    <thead>
        <tr class="first last">
            <th rowspan="1" class="a-center"><span class="nobr">SKU</span></th>
            <th rowspan="1"><span class="nobr">Product Name</span></th>
            <th rowspan="1"><span class="nobr">Short Description</span></th>
            <th rowspan="1" class="a-center">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->getItems() as $_item): ?>
        <tr class="first odd">
            <td><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getSku(), 'sku') ?></td>
            <td>
                <h2 class="product-name">
                    <a href="http://uartest.lc/simple-product1.html"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a>
                </h2>
            </td>
            <td><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?></td>
            <td class="a-center">
                <a href="#" onclick="selectSpecialShipping(<?php echo $_item->getId() ?>);" title="select special shipping">select</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    function selectSpecialShipping(productId)
    {
        new Ajax.Request('<?php echo Mage::getUrl('custom/custom/select') ?>', {
            parameters: {isAjax: 1, method: 'POST', product_id: productId},
            onLoading: function(){
//                alert('loading');
            },
            onSuccess: function(transport) {
//                alert('success');
                if (transport.responseText.isJSON()) {
                    var response = transport.responseText.evalJSON();
//                    alert(response.response);
//                    parent.special_shipping_popup.refresh();
                    parent.window.location.reload();
                }
            },
            onComplete: function () {
//                alert('complete');
            },
            onFailure: function(error) {
//                alert('error');
            }
        });
    }
</script>